source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:apiumhub/Apium-PodSpecs.git'
use_frameworks!

target 'ApiumSocialLogin_Example' do
    pod 'ApiumSocialLogin', :path => '../ApiumSocialLogin.podspec'
    pod 'Firebase/Core'
    pod 'Firebase/MLVision'
    pod 'Firebase/MLVisionBarcodeModel'
    pod 'Firebase/MLVisionTextModel'
    
    target 'ApiumSocialLogin_Tests' do
        inherit! :search_paths
    end
end
